<?php
/**
 * 后台控制器 action → 权限码（须与 permissions.code 一致）
 * 未列出的 action 仅需登录（如 menu/init、upload）
 */
return [
    'index'  => [
        'index'      => 'admin.dashboard',
        'welcome'    => 'admin.dashboard',
        'clearcache' => 'admin.dashboard',
        'spafallback'=> 'admin.dashboard',
        'reportdataaccessdenied' => 'admin.dashboard',
    ],
    'user' => [
        'index'  => 'admin.user.list',
        'create' => 'admin.user.create',
        'edit'   => 'admin.user.edit',
        'save'   => 'admin.user.edit',
        'delete' => 'admin.user.delete',
        'export' => 'admin.user.export',
        'import' => 'admin.user.import',
        'detail' => 'admin.user.list',
    ],
    'aiconfig' => [
        'configsave'       => 'admin.config',
        'testconnection'   => 'admin.config',
        'generatemeta'     => 'admin.config',
        'processdocument'  => 'admin.config',
        'processstatus'    => 'admin.config',
        'testextract'      => 'admin.config',
        'testocr'          => 'admin.config',
    ],
    'floatcontact' => [
        'configsave' => 'admin.config',
        'save'       => 'admin.config',
        'delete'     => 'admin.config',
        'status'     => 'admin.config',
        'sort'       => 'admin.config',
    ],
    'member_publish' => [
        'bootstrap'         => 'admin.document.create',
        'documentformmeta'  => 'admin.document.create',
    ],
    'spa' => [
        'bootstrap'               => 'admin.dashboard',
        'resolvehref'             => 'admin.dashboard',
        'user'                    => 'admin.dashboard',
        'changepassword'          => 'admin.dashboard',
        'totpstatus'              => 'admin.dashboard',
        'totpsetup'               => 'admin.dashboard',
        'totpenable'              => 'admin.dashboard',
        'totpdisable'             => 'admin.dashboard',
        'codes'                   => 'admin.dashboard',
        'menus'                   => 'admin.menu.list',
        'tagmeta'                 => 'admin.tag.list',
        'documentmeta'            => 'admin.document.list',
        'logmeta'                 => 'admin.log.list',
        'tagformmeta'             => 'admin.tag.list',
        'tagdetail'               => 'admin.tag.list',
        'dashboard'               => 'admin.dashboard',
        'savedashboardprefs'      => 'admin.dashboard',
        'reportdataaccessdenied'  => 'admin.dashboard',
        'configmeta'              => 'admin.config',
        'documentformmeta'        => 'admin.document.list',
        'clipboardurlinsight'     => 'admin.document.edit',
        'documenttagpicker'       => 'admin.document.list',
        'userformmeta'            => 'admin.user.list',
        'userdetail'              => 'admin.user.list',
        'roleformmeta'            => 'admin.role.list',
        'roledetail'              => 'admin.role.list',
        'memberformmeta'          => 'admin.member.list',
        'memberdetail'            => 'admin.member.list',
        'memberleveldetail'       => 'admin.member.level.list',
        'cronmeta'                => 'admin.cron.list',
        'pluginmeta'              => 'admin.plugin.list',
        'aiconfigmeta'            => 'admin.config',
        'productmeta'             => 'admin.product.manage',
        'weappplugininfo'         => 'admin.plugin.list',
        'weappusage'              => 'admin.plugin.list',
        'sitenavmeta'             => 'admin.site.nav.list',
        'sitepageformmeta'        => 'admin.site.page.list',
        'membercenterconfigmeta'  => 'admin.member.list',
        'paymentconfigmeta'       => 'plugin.payment.config',
        'paymentordersmeta'       => 'plugin.payment.use',
        'miniprogramwechatmeta'   => 'admin.config',
        'mpwechatsdkdownload'     => 'admin.config',
        'miniprogrampagemeta'     => 'admin.config',
        'miniprogrampagepreview'  => 'admin.config',
        'miniprogrampagesave'     => 'admin.config',
        'searchconfigmeta'        => 'admin.config',
        'smartsearchmeta'         => 'admin.config',
        'captchaconfigmeta'       => 'admin.config',
        'loginnoticesettingsmeta' => 'admin.config',
        'mailconfigmeta'          => 'admin.config',
        'smsconfigmeta'           => 'admin.config',
        'memberpointsconfigmeta'  => 'admin.member.list',
        'membercenterfields'      => 'admin.member.list',
        'membercenterrecharge'    => 'admin.member.list',
        'membercentercancel'      => 'admin.member.list',
        'membercenterfieldmeta'   => 'admin.member.list',
        'membercenterrechargemeta'=> 'admin.member.list',
        'seourlmeta'              => 'admin.seo.url',
        'seositemapmeta'          => 'admin.seo.sitemap',
        'seorobotsmeta'           => 'admin.seo.robots',
        'pluginscaffoldmeta'      => 'admin.plugin.list',
        'tagimportnavmeta'        => 'admin.tag.list',
        'seostaticmeta'           => 'admin.seo.url',
        'pluginweapplist'        => 'admin.plugin.list',
        'floatcontactmeta'        => 'admin.config',
        'clearcache'              => 'admin.dashboard',
        'coreupdatecheck'         => 'admin.dashboard',
        'loginnotices'            => 'admin.dashboard',
        // 登录弹窗细粒度权限（login_notices.php registry；须出现在本 map 以对齐 pv_permissions）
        'loginnoticecoreupdate'   => 'admin.notice.core_update',
        'loginnoticeformpending'  => 'admin.notice.form_pending',
        // 菜单组权限码（RBAC 树父节点，动作级码亦须双向可映射）
        'memberlevelmenu'         => 'admin.member.level',
        'membercentermenu'        => 'admin.member.center',
        'licenseactivate'         => 'admin.config',
        'licensesync'             => 'admin.config',
    ],
    'member' => [
        'index'  => 'admin.member.list',
        'create' => 'admin.member.create',
        'edit'   => 'admin.member.edit',
        'save'   => 'admin.member.edit',
        'delete' => 'admin.member.delete',
        'batchdelete' => 'admin.member.delete',
        'export' => 'admin.member.export',
        'detail' => 'admin.member.list',
    ],
    'memberlevel' => [
        'index'  => 'admin.member.level.list',
        'create' => 'admin.member.level.create',
        'edit'   => 'admin.member.level.edit',
        'save'   => 'admin.member.level.edit',
        'delete' => 'admin.member.level.delete',
        'detail' => 'admin.member.level.list',
    ],
    'membercenter' => [
        'field'          => 'admin.member.list',
        'fieldform'      => 'admin.member.list',
        'fieldsave'      => 'admin.member.edit',
        'fielddelete'    => 'admin.member.edit',
        'config'         => 'admin.member.list',
        'configsave'     => 'admin.member.edit',
        'points'         => 'admin.member.list',
        'pointsadjust'   => 'admin.member.edit',
        'pointsconfigsave' => 'admin.member.edit',
        'balance'        => 'admin.member.list',
        'balanceadjust'  => 'admin.member.edit',
        'consumption'    => 'admin.member.list',
        'orders'         => 'admin.member.list',
        'orderdetail'    => 'admin.member.list',
        'recharge'       => 'admin.member.list',
        'rechargeform'   => 'admin.member.list',
        'rechargesave'   => 'admin.member.edit',
        'rechargedelete' => 'admin.member.edit',
        'rechargesort'   => 'admin.member.edit',
        'cancel'         => 'admin.member.list',
        'cancelhandle'   => 'admin.member.edit',
    ],
    'seo' => [
        'url'            => 'admin.seo.url',
        'urlsave'        => 'admin.seo.url',
        'static'           => 'admin.seo.url',
        'staticgenerate'   => 'admin.seo.url',
        'staticbatchstart' => 'admin.seo.url',
        'staticbatchstep'  => 'admin.seo.url',
        'sitemap'        => 'admin.seo.sitemap',
        'sitemapsave'    => 'admin.seo.sitemap',
        'sitemaprebuild' => 'admin.seo.sitemap',
        'robots'      => 'admin.seo.robots',
        'robotssave'  => 'admin.seo.robots',
        'robotsreset' => 'admin.seo.robots',
        'baidupushbatch' => 'admin.seo.url',
    ],
    'eyoucms_migrate' => [
        'index'      => 'plugin.eyoucms_migrate.use',
        'configsave' => 'plugin.eyoucms_migrate.use',
        'probe'      => 'plugin.eyoucms_migrate.use',
        'run'        => 'plugin.eyoucms_migrate.run',
        'clearmap'   => 'plugin.eyoucms_migrate.run',
    ],
    'paymentconfig' => [
        'index' => 'plugin.payment.config',
    ],
    'payment' => [
        'index'              => 'plugin.payment.use',
        'orders'             => 'plugin.payment.use',
        'configsave'         => 'plugin.payment.config',
        'importwechatcerts'  => 'plugin.payment.config',
        'importalipaykeys'   => 'plugin.payment.config',
        'refundorder'        => 'plugin.payment.refund',
        'closeorder'         => 'plugin.payment.refund',
        'closestaleorders'   => 'plugin.payment.refund',
    ],
    'searchconfig' => [
        'index' => 'admin.config',
        'save'  => 'admin.config',
    ],
    'captchaconfig' => [
        'index' => 'admin.config',
        'save'  => 'admin.config',
    ],
    'loginnoticeconfig' => [
        'index' => 'admin.config',
        'save'  => 'admin.config',
    ],
    'channelsconfig' => [
        'index' => 'admin.config',
    ],
    'mailconfig' => [
        'index'         => 'admin.config',
        'save'          => 'admin.config',
        'applyethereal' => 'admin.config',
        'testsend'      => 'admin.config',
    ],
    'smsconfig' => [
        'index'    => 'admin.config',
        'save'     => 'admin.config',
        'testsend' => 'admin.config',
    ],
    'watermarkconfig' => [
        'save' => 'admin.config',
    ],
    'role' => [
        'index'  => 'admin.role.list',
        'create' => 'admin.role.create',
        'edit'   => 'admin.role.edit',
        'save'   => 'admin.role.edit',
        'delete' => 'admin.role.delete',
        'detail' => 'admin.role.list',
    ],
    'config' => [
        'index'              => 'admin.config',
        'save'               => 'admin.config',
        'savecustomvar'      => 'admin.config',
        'deletecustomvar'    => 'admin.config',
        'enablespecialchars' => 'admin.config',
    ],
    'menu' => [
        'index'  => 'admin.menu.list',
        'create' => 'admin.menu.create',
        'edit'   => 'admin.menu.edit',
        'save'   => 'admin.menu.edit',
        'sort'   => 'admin.menu.edit',
        'delete' => 'admin.menu.delete',
    ],
    'sitenav' => [
        'index'   => 'admin.site.nav.list',
        'options' => 'admin.site.nav.list',
        'save'    => 'admin.site.nav.edit',
        'sort'    => 'admin.site.nav.edit',
        'status'  => 'admin.site.nav.edit',
        'delete'  => 'admin.site.nav.edit',
    ],
    'sitepage' => [
        'index'  => 'admin.site.page.list',
        'form'   => 'admin.site.page.list',
        'save'   => 'admin.site.page.edit',
        'status' => 'admin.site.page.edit',
        'delete' => 'admin.site.page.edit',
    ],
    'siteinquiry' => [
        'index'  => 'admin.site.inquiry.list',
        'status' => 'admin.site.inquiry.edit',
        'delete' => 'admin.site.inquiry.edit',
    ],
    'accessstats' => [
        'index'      => 'admin.stats.list',
        'configsave' => 'admin.stats.config',
        'deadlinks'  => 'admin.stats.config',
    ],
    'siteform' => [
        'index'              => 'admin.form.list',
        'save'               => 'admin.form.edit',
        'delete'             => 'admin.form.edit',
        'batchdelete'        => 'admin.form.edit',
        'submissionstatus'       => 'admin.form.edit',
        'submissionbatchstatus'  => 'admin.form.edit',
        'submissiondelete'       => 'admin.form.edit',
        'submissiondetail'   => 'admin.form.list',
        'submissionexport'   => 'admin.form.list',
        'submissionexportasyncstart'   => 'admin.form.list',
        'submissionexportasyncstep'    => 'admin.form.list',
        'submissionexportasyncdownload'=> 'admin.form.list',
    ],
    'siteslide' => [
        'index'  => 'admin.site.slide.list',
        'save'   => 'admin.site.slide.edit',
        'sort'   => 'admin.site.slide.edit',
        'status' => 'admin.site.slide.edit',
        'delete' => 'admin.site.slide.edit',
    ],
    'siteadslot' => [
        'index'        => 'admin.site.slide.list',
        'suggestcode'  => 'admin.site.slide.list',
        'save'         => 'admin.site.slide.edit',
        'delete'       => 'admin.site.slide.edit',
    ],
    'item' => [
        'index'               => 'admin.item.list',
        'meta'                => 'admin.item.list',
        'save'                => 'admin.item.edit',
        'delete'              => 'admin.item.edit',
        'export'              => 'admin.item.export',
        'duplicate'           => 'admin.item.edit',
        'import'              => 'admin.item.edit',
        'importpreview'       => 'admin.item.edit',
        'bulkstatus'          => 'admin.item.edit',
        'bulkdelete'          => 'admin.item.edit',
        'itemsbydocument'     => 'admin.item.list',
        'exportasyncstart'    => 'admin.item.export',
        'exportasyncstep'     => 'admin.item.export',
        'exportasyncdownload' => 'admin.item.export',
        'variantsbyitem'      => 'admin.item.variant.list',
        'variantsave'         => 'admin.item.variant.edit',
        'variantdelete'       => 'admin.item.variant.edit',
        'accessoriesbyitem'   => 'admin.item.list',
        'syncaccessories'     => 'admin.item.edit',
        'documentsbyitem'     => 'admin.item.list',
    ],
    'sitedomain' => [
        'index'         => 'admin.site.domain.list',
        'meta'          => 'admin.site.domain.list',
        'tagsforgroup'  => 'admin.site.domain.list',
        'save'          => 'admin.site.domain.edit',
        'sort'   => 'admin.site.domain.edit',
        'status' => 'admin.site.domain.edit',
        'delete' => 'admin.site.domain.edit',
    ],
    'sitelink' => [
        'index'  => 'admin.site.link.list',
        'save'   => 'admin.site.link.edit',
        'sort'   => 'admin.site.link.edit',
        'status' => 'admin.site.link.edit',
        'delete' => 'admin.site.link.edit',
        'batchdelete' => 'admin.site.link.edit',
    ],
    'document' => [
        'index'        => 'admin.document.list',
        'create'       => 'admin.document.create',
        'edit'         => 'admin.document.edit',
        'save'         => 'admin.document.edit',
        'status'       => 'admin.document.edit',
        'delete'       => 'admin.document.delete',
        'batchdelete'  => 'admin.document.delete',
        'batchstatus'  => 'admin.document.edit',
        'batchtags'    => 'admin.document.edit',
        'export'       => 'admin.document.export',
        'exportjson'   => 'admin.document.export',
        'import'       => 'admin.document.import',
        'importjson'   => 'admin.document.import',
        'upload'       => 'admin.document.edit',
        'gettags'      => 'admin.document.list',
        'saveeditorsurfaceorder' => 'admin.document.edit',
        'batchattr'    => 'admin.document.edit',
        'batchseo'     => 'admin.document.edit',
        'restore'      => 'admin.document.edit',
        'purgerecycle' => 'admin.document.delete',
        'emptyrecycle' => 'admin.document.delete',
        'bulkreplacepreview' => 'admin.document.edit',
        'bulkreplace'        => 'admin.document.edit',
        'qrcode'             => 'admin.document.list',
        'blockmeta'          => 'admin.document.edit',
        'blockpreview'       => 'admin.document.edit',
        'clipboardurlinsight'=> 'admin.document.edit',
    ],
    'tag' => [
        'index'      => 'admin.tag.list',
        'create'     => 'admin.tag.create',
        'edit'       => 'admin.tag.edit',
        'save'       => 'admin.tag.edit',
        'sort'       => 'admin.tag.edit',
        'status'     => 'admin.tag.edit',
        'delete'     => 'admin.tag.delete',
        'merge'      => 'admin.tag.merge',
        'reconcile'  => 'admin.tag.edit',
        'options'    => 'admin.tag.list',
        'batchdelete' => 'admin.tag.delete',
        'batchstatus' => 'admin.tag.edit',
        'batchreconcile' => 'admin.tag.edit',
        'parentoptions' => 'admin.tag.list',
        'importnav' => 'admin.tag.edit',
        'importnavpreview' => 'admin.tag.edit',
        'importnavexecute' => 'admin.tag.edit',
        'detail'           => 'admin.tag.list',
    ],
    'taggroup' => [
        'index'  => 'admin.tag.list',
        'meta'   => 'admin.tag.list',
        'save'   => 'admin.tag.edit',
        'sort'   => 'admin.tag.edit',
        'status' => 'admin.tag.edit',
        'delete' => 'admin.tag.edit',
    ],
    'log' => [
        'index'    => 'admin.log.list',
        'export'   => 'admin.log.list',
        'detail'   => 'admin.log.list',
        'delete'   => 'admin.log.purge',
        'cleanup'  => 'admin.log.purge',
        'purgeall' => 'admin.log.purge',
    ],
    'media' => [
        'index'              => 'admin.media.list',
        'meta'               => 'admin.media.list',
        'list'               => 'admin.media.list',
        'enterprisemeta'     => 'admin.media.list',
        'enterpriselist'     => 'admin.media.list',
        'enterprisesave'     => 'admin.media.list',
        'enterprisearchive'  => 'admin.media.list',
        'enterprisebatcharchive' => 'admin.media.list',
        'enterprisedelete'   => 'admin.media.delete',
        'enterprisebatchdelete' => 'admin.media.delete',
        'enterpriseentitysave'     => 'admin.media.list',
        'enterpriseentitylist'     => 'admin.media.list',
        'enterpriseentityarchive'  => 'admin.media.delete',
        'enterpriseentityrestore'  => 'admin.media.delete',
        'enterpriseentitydelete'   => 'admin.media.delete',
        'enterpriseentityconsolidate' => 'admin.media.delete',
        'enterpriseexport'         => 'admin.media.list',
        'delete'             => 'admin.media.delete',
        'batchdelete'        => 'admin.media.delete',
        'move'               => 'admin.media.delete',
    ],
    'upload' => [
        'config'        => 'admin.media.list',
        'check'         => 'admin.media.list',
        'chunkinit'     => 'admin.media.list',
        'chunkstatus'   => 'admin.media.list',
        'chunk'         => 'admin.media.list',
        'chunkcomplete' => 'admin.media.list',
        'image'         => 'admin.media.list',
        'file'          => 'admin.media.list',
        'video'         => 'admin.media.list',
    ],
    'debug' => [
        'captcha' => 'admin.dashboard',
    ],
    'plugin' => [
        'index'     => 'admin.plugin.list',
        'cloud'     => 'admin.plugin.list',
        'market'    => 'admin.plugin.list',
        'marketupdates' => 'admin.plugin.list',
        'purchased' => 'admin.plugin.list',
        'preflight' => 'admin.plugin.list',
        'securitypolicy' => 'admin.plugin.list',
        'auditpackage' => 'admin.plugin.manage',
        'marketauditpackage' => 'admin.plugin.list',
        'marketsecuritystatus' => 'admin.plugin.list',
        'marketsecuritysync' => 'admin.plugin.manage',
        'refreshcapabilitysnapshots' => 'admin.plugin.manage',
        'togglesafemode' => 'admin.plugin.manage',
        'gatewayaudit' => 'admin.plugin.list',
        'capabilitystatus' => 'admin.plugin.list',
        'installbackups' => 'admin.plugin.manage',
        'restoreinstallbackup' => 'admin.plugin.manage',
        'skucatalog' => 'admin.plugin.manage',
        'skucatalogactive' => 'admin.plugin.manage',
        'exportencoded' => 'admin.plugin.manage',
        'exportlicense' => 'admin.plugin.manage',
        'importlicense' => 'admin.plugin.manage',
        'install'   => 'admin.plugin.manage',
        'upload'    => 'admin.plugin.manage',
        'marketacquire' => 'admin.plugin.manage',
        'enable'    => 'admin.plugin.manage',
        'disable'   => 'admin.plugin.manage',
        'upgrade'   => 'admin.plugin.manage',
        'grant'     => 'admin.plugin.manage',
        'revokeentitlement' => 'admin.plugin.manage',
        'createscaffold' => 'admin.plugin.manage',
        'scaffold'       => 'admin.plugin.list',
        'suggestpackage' => 'admin.plugin.list',
        'commerce'       => 'admin.plugin.manage',
        'skus'           => 'admin.plugin.manage',
        'orders'         => 'admin.plugin.manage',
        'createorder'    => 'admin.plugin.manage',
        'confirmorder'   => 'admin.plugin.manage',
        'rollbackorder'  => 'plugin.payment.refund',
        'refundorder'    => 'plugin.payment.refund',
        'orderstatus'    => 'admin.plugin.manage',
        'commercereport' => 'admin.plugin.manage',
        'walletledger'   => 'admin.plugin.manage',
        'walletcredit'   => 'admin.plugin.manage',
        'refundrequests' => 'admin.plugin.manage',
        'refundrequestsubmit' => 'admin.plugin.manage',
        'approverefundrequest' => 'plugin.payment.refund',
        'rejectrefundrequest'  => 'plugin.payment.refund',
        'commercialpricingmeta' => 'admin.plugin.manage',
        'commercialpricingform' => 'admin.plugin.manage',
        'updatecommercialpricing' => 'admin.plugin.manage',
        'workbench' => 'admin.plugin.list',
        'workbenchmeta' => 'admin.plugin.list',
        'workbenchgateways' => 'admin.plugin.list',
        'workbenchextensionpoints' => 'admin.plugin.list',
        'workbenchvalidatemanifest' => 'admin.plugin.manage',
        'upgradepreflight' => 'admin.plugin.list',
        'capabilities' => 'admin.plugin.list',
        'marketapplyupdates' => 'admin.plugin.manage',
        'export'    => 'admin.plugin.manage',
        'uninstall' => 'admin.plugin.manage',
        'weappplugininfo'   => 'admin.plugin.list',
        'weappusage'        => 'admin.plugin.list',
        'identifiercheck'   => 'admin.plugin.list',
        'packagecheck'      => 'admin.plugin.list',
        'naminglookup'      => 'admin.plugin.list',
        'namingpolicy'      => 'admin.plugin.list',
        'weapplist'         => 'admin.plugin.list',
    ],
    'backup' => [
        'index'    => 'admin.backup.list',
        'tables'   => 'admin.backup.list',
        'create'   => 'admin.backup.create',
        'download' => 'admin.backup.list',
        'delete'   => 'admin.backup.create',
        'restore'  => 'admin.backup.create',
    ],
    'sqlconsole' => [
        'meta'    => 'admin.sql_console',
        'execute' => 'admin.sql_console.run',
        'import'  => 'admin.sql_console.run',
    ],
    'dataretention' => [
        'index' => 'admin.cron.list',
        'save'  => 'admin.cron.manage',
    ],
    'cron' => [
        'index'  => 'admin.cron.list',
        'save'   => 'admin.cron.manage',
        'status' => 'admin.cron.manage',
        'delete' => 'admin.cron.manage',
        'run'    => 'admin.cron.manage',
    ],
    'upgrade' => [
        'meta'  => 'admin.plugin.manage',
        'check' => 'admin.dashboard',
        'run'   => 'admin.plugin.manage',
        'licenseactivate' => 'admin.config',
        'licensesync'       => 'admin.config',
    ],
    'miniprogram' => [
        'pagepreview' => 'admin.config',
        'pagesave'    => 'admin.config',
        'wechatsdkdownload' => 'admin.config',
    ],
    'cockpit' => [
        'index' => 'admin.cockpit.view',
    ],
    'favorite' => [
        'index'      => 'admin.favorite.list',
        'configsave' => 'admin.favorite.config',
    ],
    'socialauth' => [
        'index'      => 'plugin.social_auth.use',
        'configsave' => 'plugin.social_auth.use',
    ],
    'product' => [
        'index'       => 'admin.product.manage',
        'paramsave'   => 'admin.product.manage',
        'paramdelete' => 'admin.product.manage',
        'paramsort'   => 'admin.product.manage',
        'configsave'  => 'admin.product.manage',
        'groupsave'   => 'admin.product.manage',
        'groupdelete' => 'admin.product.manage',
        'groupbatchstatus' => 'admin.product.manage',
        'groupbatchdelete' => 'admin.product.manage',
        'syncofficialitems' => 'admin.product.manage',
    ],
    'searchindex' => [
        'enginestatus'            => 'admin.config',
        'reindex'                 => 'admin.config',
        'rebuildsearchtextstatus' => 'admin.config',
    ],
    'miniprogramconfig' => [
        'index' => 'admin.config',
    ],
    'miniprogrampage' => [
        'index' => 'admin.config',
    ],
    'insights' => [
        'index'   => 'admin.insights.view',
        'cockpit' => 'admin.insights.view',
    ],
];
