<?php

/**
 * 卸载时必 DROP 的业务表（含改名前后旧表）
 * 键 = plugins.identifier；无 weapp 目录时仍生效（幽灵登记）
 *
 * @return array<string, list<string>>
 */
return [
    'download' => [
        'weapp_download_bundles',
        'weapp_download_items',
        'weapp_download_purchases',
        'weapp_download_point_unlocks',
        'weapp_download_tokens',
        'weapp_download_files',
        'weapp_download_logs',
    ],
    'doc_bundle' => [
        'weapp_doc_bundle_bundles',
        'weapp_doc_bundle_items',
        'weapp_doc_bundle_purchases',
        'weapp_doc_bundle_point_unlocks',
        'weapp_doc_bundle_logs',
        'weapp_doc_bundle_tokens',
        // 旧标 download
        'weapp_download_bundles',
        'weapp_download_items',
        'weapp_download_purchases',
        'weapp_download_point_unlocks',
        'weapp_download_tokens',
        'weapp_download_files',
        'weapp_download_logs',
    ],
    'video' => [
        'weapp_video_items',
        'weapp_video_series',
        'weapp_video_episodes',
        'weapp_video_sources',
        'weapp_video_grants',
        'weapp_video_watch_progress',
        'weapp_video_play_daily',
        'weapp_video_parse_log',
        'weapp_video_episode_play_daily',
    ],
    'doc_vod' => [
        'weapp_doc_vod_items',
        'weapp_doc_vod_series',
        'weapp_doc_vod_episodes',
        'weapp_doc_vod_sources',
        'weapp_doc_vod_grants',
        'weapp_doc_vod_watch_progress',
        'weapp_doc_vod_play_daily',
        'weapp_doc_vod_parse_log',
        'weapp_doc_vod_episode_play_daily',
        'weapp_video_items',
        'weapp_video_series',
        'weapp_video_episodes',
        'weapp_video_sources',
        'weapp_video_grants',
        'weapp_video_watch_progress',
        'weapp_video_play_daily',
        'weapp_video_parse_log',
        'weapp_video_episode_play_daily',
    ],
    'ask' => [
        'weapp_ask_items',
    ],
    'doc_ask' => [
        'weapp_doc_ask_items',
        'weapp_ask_items',
    ],
    'gallery' => [
        'weapp_gallery_groups',
        'weapp_gallery_items',
    ],
    'doc_gallery' => [
        'weapp_doc_gallery_groups',
        'weapp_doc_gallery_items',
        'weapp_gallery_groups',
        'weapp_gallery_items',
    ],
    'talent' => [
        'weapp_talent_items',
    ],
    'doc_talent' => [
        'weapp_doc_talent_items',
        'weapp_talent_items',
    ],
    'comment' => [
        'weapp_comments',
        'weapp_comment_likes',
        'weapp_comment_levels',
    ],
    'doc_comment' => [
        'weapp_doc_comment_comments',
        'weapp_doc_comment_likes',
        'weapp_doc_comment_levels',
        'weapp_comments',
        'weapp_comment_likes',
        'weapp_comment_levels',
    ],
    'thumb' => [],
    'doc_thumb' => [],
    'ai_ppt' => [
        'ai_ppt_decks',
        'ai_ppt_exports',
        'ai_ppt_share_hits',
        'ai_ppt_snapshots',
        'ai_ppt_theme_prefs',
        'ai_ppt_usage_log',
    ],
    'shop' => [
        'weapp_shop_offers',
        'weapp_shop_orders',
        'weapp_shop_order_lines',
        'weapp_shop_spec_defs',
        'weapp_shop_skus',
        'weapp_shop_carts',
        'weapp_shop_cart_items',
        'weapp_shop_addresses',
        'weapp_shop_freight_templates',
        'weapp_shop_coupons',
        'weapp_shop_refunds',
        'weapp_shop_coupon_uses',
        'weapp_shop_bundles',
        'weapp_shop_bundle_lines',
        'weapp_shop_seckill_sessions',
        'weapp_shop_seckill_items',
        'weapp_shop_favorites',
        'weapp_shop_shipments',
        'weapp_shop_invoice_requests',
        'weapp_shop_merchants',
    ],
];
