<?php
/**
 * 限流策略 SSOT（滑动窗口 / 冷却；站点覆盖见 rate_limit_policy_overrides）
 */
declare(strict_types=1);

return [
    'enabled'        => true,
    'overrides_key'    => 'rate_limit_policy_overrides',
    'window_seconds'   => 60,
    'api_match_order'  => [
        'api.auth',
        'api.pay',
        'api.search',
        'api.favorite',
        'api.write',
        'api.default',
    ],
    'policies' => [
        'front.cc' => [
            'label'          => '前台 CC 防护',
            'hint'           => '限制前台 HTML 页面每分钟请求次数，减轻恶意刷量；不含后台管理、公开 API 与 /install 安装向导。',
            'group'          => '前台防护',
            'layer'          => 'front_html',
            'enabled'        => true,
            'bypass'         => false,
            'mode'           => 'window',
            'max_requests'   => 120,
            'min_requests'   => 30,
            'window_seconds' => 60,
            'dimension'      => 'ip',
            'response'       => 'html_plain',
            'message'        => 'Too Many Requests',
            'admin_editable' => true,
        ],
        'front.search' => [
            'label'          => '前台搜索页',
            'hint'           => '/search 页面按 IP 限流；与搜索设置中的「搜索限流」同步。',
            'group'          => '前台防护',
            'layer'          => 'front_search',
            'enabled'        => true,
            'bypass'         => false,
            'mode'           => 'window',
            'max_requests'   => 5,
            'window_seconds' => 60,
            'lock_seconds'   => 120,
            'dimension'      => 'ip',
            'ip_scope'       => 'front_search',
            'response'       => 'html_page',
            'message'        => '请求过于频繁，请稍后再试',
            'admin_editable' => true,
        ],
        'api.default' => [
            'label'          => '公开 API 默认桶',
            'hint'           => '未命中细分桶时的默认限额（单 IP）。后台 admin/* 已豁免。',
            'group'          => '公开 API',
            'layer'          => 'api',
            'enabled'        => true,
            'bypass'         => false,
            'mode'           => 'window',
            'max_requests'   => 120,
            'window_seconds' => 60,
            'dimension'      => 'ip',
            'api_bucket'     => 'default',
            'patterns'       => [],
            'response'       => 'json_api',
            'message'        => '请求过于频繁，请稍后再试',
            'admin_editable' => true,
        ],
        'api.auth' => [
            'label'          => '登录 / 登出',
            'hint'           => '会员登录、登出、小程序登录等认证接口。',
            'group'          => '公开 API',
            'layer'          => 'api',
            'enabled'        => true,
            'mode'           => 'window',
            'max_requests'   => 20,
            'window_seconds' => 60,
            'dimension'      => 'ip',
            'api_bucket'     => 'auth',
            'patterns'       => [
                'member/mp-wechat/login',
                'member/mp-wechat/logout',
                'member/logout',
            ],
            'response'       => 'json_api',
            'admin_editable' => true,
        ],
        'api.pay' => [
            'label'          => '会员支付写',
            'hint'           => '充值下单等写接口；已登录时按会员 ID 分桶。',
            'group'          => '公开 API',
            'layer'          => 'api',
            'enabled'        => true,
            'mode'           => 'window',
            'max_requests'   => 30,
            'window_seconds' => 60,
            'dimension'      => 'user_id',
            'rate_by_user'   => true,
            'api_bucket'     => 'pay',
            'patterns'       => [
                'member/recharge/pay',
                'member/recharge/order/',
            ],
            'response'       => 'json_api',
            'admin_editable' => true,
        ],
        'api.search' => [
            'label'          => '搜索 API',
            'hint'           => '智能搜索、联想、点击上报等接口。',
            'group'          => '公开 API',
            'layer'          => 'api',
            'enabled'        => true,
            'mode'           => 'window',
            'max_requests'   => 60,
            'window_seconds' => 60,
            'dimension'      => 'ip',
            'api_bucket'     => 'search',
            'patterns'       => [
                'search/smart',
                'search/suggest',
                'search/click',
            ],
            'response'       => 'json_api',
            'admin_editable' => true,
        ],
        'api.favorite' => [
            'label'          => '点赞 / 收藏',
            'hint'           => '已登录时按会员 ID 分桶。',
            'group'          => '公开 API',
            'layer'          => 'api',
            'enabled'        => true,
            'mode'           => 'window',
            'max_requests'   => 20,
            'window_seconds' => 60,
            'dimension'      => 'user_id',
            'rate_by_user'   => true,
            'api_bucket'     => 'favorite',
            'patterns'       => [
                'favorite/like',
                'favorite/collect',
            ],
            'response'       => 'json_api',
            'admin_editable' => true,
        ],
        'api.write' => [
            'label'          => '上传 / 表单 / 埋点',
            'hint'           => '上传、表单提交、统计 beacon；已登录时按会员 ID 分桶。',
            'group'          => '公开 API',
            'layer'          => 'api',
            'enabled'        => true,
            'mode'           => 'window',
            'max_requests'   => 40,
            'window_seconds' => 60,
            'dimension'      => 'user_id',
            'rate_by_user'   => true,
            'api_bucket'     => 'write',
            'patterns'       => [
                'upload',
                'forms/submit',
                'stats/beacon',
            ],
            'response'       => 'json_api',
            'admin_editable' => true,
        ],
        'captcha.image' => [
            'label'          => '验证码出图',
            'hint'           => '按 IP + 场景限制验证码图片请求频率。',
            'group'          => '认证与安全',
            'layer'          => 'service',
            'enabled'        => true,
            'mode'           => 'window',
            'max_requests'   => 40,
            'window_seconds' => 60,
            'dimension'      => 'scene_ip',
            'response'       => 'message',
            'message'        => '验证码请求过于频繁，请稍后再试',
            'admin_editable' => true,
            'config_path'    => 'captcha.image_rate_limit',
        ],
        'pay.notify' => [
            'label'          => '支付异步回调',
            'hint'           => '微信/支付宝等支付平台通知入口，按来源 IP 限流。',
            'group'          => '支付',
            'layer'          => 'pay_notify',
            'enabled'        => true,
            'mode'           => 'window',
            'max_requests'   => 120,
            'window_seconds' => 60,
            'dimension'      => 'ip',
            'ip_scope'       => 'pay_notify',
            'response'       => 'html_plain',
            'message'        => 'Too Many Requests',
            'admin_editable' => true,
            'env_keys'       => [
                'enabled' => 'PAY_NOTIFY_RATE_LIMIT',
                'max'     => 'PAY_NOTIFY_RATE_MAX',
                'window'  => 'PAY_NOTIFY_RATE_WINDOW',
            ],
        ],
        'cron.tick' => [
            'label'          => 'Cron Webhook',
            'hint'           => '计划任务 HTTP 触发入口，防止探测与滥用。',
            'group'          => '运维',
            'layer'          => 'service',
            'enabled'        => true,
            'mode'           => 'window',
            'max_requests'   => 6,
            'window_seconds' => 60,
            'dimension'      => 'ip',
            'ip_scope'       => 'cron_tick',
            'response'       => 'json_api',
            'admin_editable' => true,
        ],
        'member.password_reset' => [
            'label'          => '账户找回',
            'hint'           => '会员邮件找回密码 / 忘记登录名，按 IP 限制申请次数。',
            'group'          => '会员',
            'layer'          => 'service',
            'enabled'        => true,
            'mode'           => 'window',
            'max_requests'   => 5,
            'window_seconds' => 3600,
            'dimension'      => 'ip',
            'response'       => 'service_result',
            'message'        => '操作过于频繁，请稍后再试',
            'admin_editable' => true,
        ],
        'admin.bulk_replace' => [
            'label'            => '全库替换执行',
            'hint'             => '后台批量替换内容，按管理员账号冷却。',
            'group'            => '后台运维',
            'layer'            => 'service',
            'enabled'          => true,
            'mode'             => 'cooldown',
            'cooldown_seconds' => 60,
            'dimension'        => 'user_id',
            'response'         => 'message',
            'message'          => '操作过于频繁，请稍后再执行全库替换',
            'admin_editable'   => true,
        ],
        'admin.trusted' => [
            'label'    => '后台 REST（可信通道）',
            'hint'     => '已走登录 + CSRF，不与匿名 API 共用 IP 桶；仅登记，不实际计数。',
            'group'    => '后台运维',
            'layer'    => 'api',
            'enabled'  => true,
            'bypass'   => true,
            'admin_editable' => false,
        ],
    ],
];
