<?php
/**
 * 元舟 PivArk — 企业全域原子化数字资产中枢
 * (c) 2024-2026 pivark.com. All rights reserved.
 * Author: Angelo
 * 未经允许，不可用于商业用途。
 */
declare(strict_types=1);

return array (
  0 => 
  array (
    'id' => 1,
    'title' => '工作台',
    'permission_code' => NULL,
    'parent_id' => 0,
    'icon' => 'fa fa-home',
    'route' => '',
    'params' => NULL,
    'sort' => 10,
    'status' => 0,
  ),
  1 => 
  array (
    'id' => 2,
    'title' => '系统设置',
    'permission_code' => NULL,
    'parent_id' => 0,
    'icon' => 'fa fa-cog',
    'route' => '',
    'params' => NULL,
    'sort' => 50,
    'status' => 1,
  ),
  2 => 
  array (
    'id' => 3,
    'title' => '后台账号',
    'permission_code' => NULL,
    'parent_id' => 19,
    'icon' => 'fa fa-users',
    'route' => '/system/user',
    'params' => NULL,
    'sort' => 1,
    'status' => 1,
  ),
  3 => 
  array (
    'id' => 4,
    'title' => '角色管理',
    'permission_code' => NULL,
    'parent_id' => 19,
    'icon' => 'fa fa-shield',
    'route' => '/system/role',
    'params' => NULL,
    'sort' => 2,
    'status' => 1,
  ),
  4 => 
  array (
    'id' => 5,
    'title' => '系统配置',
    'permission_code' => NULL,
    'parent_id' => 2,
    'icon' => 'fa fa-gears',
    'route' => '/system/config',
    'params' => NULL,
    'sort' => 1,
    'status' => 1,
  ),
  5 => 
  array (
    'id' => 6,
    'title' => '后台菜单',
    'permission_code' => NULL,
    'parent_id' => 2,
    'icon' => 'fa fa-list',
    'route' => '/system/menu',
    'params' => NULL,
    'sort' => 2,
    'status' => 1,
  ),
  6 => 
  array (
    'id' => 10,
    'title' => '内容发布',
    'permission_code' => NULL,
    'parent_id' => 0,
    'icon' => 'fa fa-edit',
    'route' => '',
    'params' => NULL,
    'sort' => 20,
    'status' => 1,
  ),
  7 => 
  array (
    'id' => 11,
    'title' => '文档列表',
    'permission_code' => 'admin.document.list',
    'parent_id' => 10,
    'icon' => 'fa fa-file-text-o',
    'route' => '/content/document',
    'params' => NULL,
    'sort' => 3,
    'status' => 1,
  ),
  8 => 
  array (
    'id' => 12,
    'title' => '发布文档',
    'permission_code' => 'admin.document.create',
    'parent_id' => 10,
    'icon' => 'fa fa-plus',
    'route' => '/content/document/create',
    'params' => NULL,
    'sort' => 4,
    'status' => 1,
  ),
  9 => 
  array (
    'id' => 13,
    'title' => '标签',
    'permission_code' => 'admin.tag.list',
    'parent_id' => 10,
    'icon' => 'fa fa-tags',
    'route' => '/content/tag',
    'params' => NULL,
    'sort' => 2,
    'status' => 1,
  ),
  10 => 
  array (
    'id' => 14,
    'title' => '素材库',
    'permission_code' => 'admin.media.list',
    'parent_id' => 10,
    'icon' => 'fa fa-picture-o',
    'route' => '/system/media',
    'params' => NULL,
    'sort' => 5,
    'status' => 1,
  ),
  11 => 
  array (
    'id' => 15,
    'title' => '操作日志',
    'permission_code' => 'admin.log',
    'parent_id' => 20,
    'icon' => 'fa fa-history',
    'route' => '/system/log',
    'params' => NULL,
    'sort' => 5,
    'status' => 1,
  ),
  12 => 
  array (
    'id' => 16,
    'title' => '插件中心',
    'permission_code' => 'admin.plugin.list',
    'parent_id' => 0,
    'icon' => 'fa fa-plug',
    'route' => '',
    'params' => NULL,
    'sort' => 35,
    'status' => 1,
  ),
  13 => 
  array (
    'id' => 17,
    'title' => '数据备份',
    'permission_code' => 'admin.backup',
    'parent_id' => 20,
    'icon' => 'fa fa-database',
    'route' => '/system/backup',
    'params' => NULL,
    'sort' => 4,
    'status' => 1,
  ),
  14 => 
  array (
    'id' => 18,
    'title' => '概览',
    'permission_code' => 'admin.dashboard',
    'parent_id' => 1,
    'icon' => 'fa fa-tachometer',
    'route' => '/dashboard/welcome',
    'params' => NULL,
    'sort' => 1,
    'status' => 0,
  ),
  15 => 
  array (
    'id' => 19,
    'title' => '用户权限',
    'permission_code' => NULL,
    'parent_id' => 0,
    'icon' => 'fa fa-users',
    'route' => '',
    'params' => NULL,
    'sort' => 45,
    'status' => 1,
  ),
  16 => 
  array (
    'id' => 20,
    'title' => '运维工具',
    'permission_code' => NULL,
    'parent_id' => 0,
    'icon' => 'fa fa-life-ring',
    'route' => '',
    'params' => NULL,
    'sort' => 60,
    'status' => 1,
  ),
  17 => 
  array (
    'id' => 23,
    'title' => '标签组',
    'permission_code' => 'admin.tag.list',
    'parent_id' => 10,
    'icon' => 'fa fa-folder-o',
    'route' => '/content/tag-group',
    'params' => NULL,
    'sort' => 5,
    'status' => 1,
  ),
  18 => 
  array (
    'id' => 24,
    'title' => '网站栏目',
    'permission_code' => 'admin.site.nav',
    'parent_id' => 10,
    'icon' => 'fa fa-sitemap',
    'route' => '/site/nav',
    'params' => NULL,
    'sort' => 90,
    'status' => 1,
  ),
  19 => 
  array (
    'id' => 25,
    'title' => '单页管理',
    'permission_code' => 'admin.site.page',
    'parent_id' => 10,
    'icon' => 'fa fa-file-o',
    'route' => '/site/page',
    'params' => NULL,
    'sort' => 9,
    'status' => 1,
  ),
  20 => 
  array (
    'id' => 26,
    'title' => '广告管理',
    'permission_code' => 'admin.site.slide',
    'parent_id' => 64,
    'icon' => 'fa fa-bullhorn',
    'route' => '/site/ads',
    'params' => NULL,
    'sort' => 3,
    'status' => 1,
  ),
  21 => 
  array (
    'id' => 27,
    'title' => '咨询留言',
    'permission_code' => 'admin.site.inquiry.list',
    'parent_id' => 64,
    'icon' => 'fa fa-envelope-o',
    'route' => '/site/form/submissions/contact',
    'params' => NULL,
    'sort' => 7,
    'status' => 0,
  ),
  22 => 
  array (
    'id' => 28,
    'title' => '站点搭建',
    'permission_code' => 'admin.site',
    'parent_id' => 0,
    'icon' => 'fa fa-sitemap',
    'route' => '',
    'params' => NULL,
    'sort' => 25,
    'status' => 0,
  ),
  23 => 
  array (
    'id' => 29,
    'title' => '定时任务',
    'permission_code' => 'admin.cron',
    'parent_id' => 20,
    'icon' => 'fa fa-clock-o',
    'route' => '/system/cron',
    'params' => NULL,
    'sort' => 1,
    'status' => 1,
  ),
  24 => 
  array (
    'id' => 30,
    'title' => '友情链接',
    'permission_code' => 'admin.site.link',
    'parent_id' => 64,
    'icon' => 'fa fa-link',
    'route' => '/site/link',
    'params' => NULL,
    'sort' => 6,
    'status' => 1,
  ),
  25 => 
  array (
    'id' => 31,
    'title' => '多域名分站',
    'permission_code' => 'admin.site.domain',
    'parent_id' => 28,
    'icon' => 'fa fa-globe',
    'route' => '/site/domain',
    'params' => NULL,
    'sort' => 3,
    'status' => 0,
  ),
  26 => 
  array (
    'id' => 32,
    'title' => '会员列表',
    'permission_code' => 'admin.member.list',
    'parent_id' => 35,
    'icon' => 'fa fa-user-o',
    'route' => '/member/list',
    'params' => NULL,
    'sort' => 2,
    'status' => 1,
  ),
  27 => 
  array (
    'id' => 33,
    'title' => '下载管理',
    'permission_code' => 'plugin.doc_bundle.use',
    'parent_id' => 10,
    'icon' => 'fa fa-download',
    'route' => '/weapp/host/doc_bundle/resources',
    'params' => NULL,
    'sort' => 6,
    'status' => 0,
  ),
  28 => 
  array (
    'id' => 34,
    'title' => '会员级别',
    'permission_code' => 'admin.member.level.list',
    'parent_id' => 35,
    'icon' => 'fa fa-star-o',
    'route' => '/member/level',
    'params' => NULL,
    'sort' => 3,
    'status' => 1,
  ),
  29 => 
  array (
    'id' => 35,
    'title' => '会员中心',
    'permission_code' => NULL,
    'parent_id' => 0,
    'icon' => 'fa fa-user-circle',
    'route' => '',
    'params' => NULL,
    'sort' => 40,
    'status' => 1,
  ),
  30 => 
  array (
    'id' => 36,
    'title' => '会员字段',
    'permission_code' => 'admin.member.list',
    'parent_id' => 35,
    'icon' => 'fa fa-circle-o',
    'route' => '/member/center/field',
    'params' => NULL,
    'sort' => 4,
    'status' => 1,
  ),
  31 => 
  array (
    'id' => 37,
    'title' => '功能配置',
    'permission_code' => 'admin.member.list',
    'parent_id' => 35,
    'icon' => 'fa fa-circle-o',
    'route' => '/member/center/config',
    'params' => NULL,
    'sort' => 1,
    'status' => 1,
  ),
  32 => 
  array (
    'id' => 38,
    'title' => '积分管理',
    'permission_code' => 'admin.member.list',
    'parent_id' => 35,
    'icon' => 'fa fa-circle-o',
    'route' => '/member/center/points',
    'params' => NULL,
    'sort' => 6,
    'status' => 1,
  ),
  33 => 
  array (
    'id' => 39,
    'title' => '充值套餐',
    'permission_code' => 'admin.member.list',
    'parent_id' => 35,
    'icon' => 'fa fa-circle-o',
    'route' => '/member/center/recharge',
    'params' => NULL,
    'sort' => 5,
    'status' => 1,
  ),
  34 => 
  array (
    'id' => 40,
    'title' => '会员注销',
    'permission_code' => 'admin.member.list',
    'parent_id' => 35,
    'icon' => 'fa fa-circle-o',
    'route' => '/member/center/cancel',
    'params' => NULL,
    'sort' => 9,
    'status' => 1,
  ),
  35 => 
  array (
    'id' => 41,
    'title' => '搜索收录',
    'permission_code' => NULL,
    'parent_id' => 64,
    'icon' => 'fa fa-search',
    'route' => '/seo/url',
    'params' => NULL,
    'sort' => 8,
    'status' => 1,
  ),
  36 => 
  array (
    'id' => 42,
    'title' => 'URL配置',
    'permission_code' => 'admin.seo.url',
    'parent_id' => 41,
    'icon' => 'fa fa-circle-o',
    'route' => '/seo/url',
    'params' => NULL,
    'sort' => 1,
    'status' => 1,
  ),
  37 => 
  array (
    'id' => 43,
    'title' => 'Sitemap',
    'permission_code' => 'admin.seo.sitemap',
    'parent_id' => 41,
    'icon' => 'fa fa-circle-o',
    'route' => '/seo/sitemap',
    'params' => NULL,
    'sort' => 3,
    'status' => 1,
  ),
  38 => 
  array (
    'id' => 44,
    'title' => 'Robots',
    'permission_code' => 'admin.seo.robots',
    'parent_id' => 41,
    'icon' => 'fa fa-circle-o',
    'route' => '/seo/robots',
    'params' => NULL,
    'sort' => 4,
    'status' => 1,
  ),
  39 => 
  array (
    'id' => 45,
    'title' => 'HTML生成',
    'permission_code' => 'admin.seo.url',
    'parent_id' => 41,
    'icon' => 'fa fa-circle-o',
    'route' => '/seo/static',
    'params' => NULL,
    'sort' => 2,
    'status' => 1,
  ),
  40 => 
  array (
    'id' => 46,
    'title' => '消费记录',
    'permission_code' => 'admin.member.list',
    'parent_id' => 35,
    'icon' => 'fa fa-shopping-cart',
    'route' => '/member/center/consumption',
    'params' => NULL,
    'sort' => 7,
    'status' => 1,
  ),
  41 => 
  array (
    'id' => 47,
    'title' => '支付订单',
    'permission_code' => 'admin.member.list',
    'parent_id' => 35,
    'icon' => 'fa fa-list-alt',
    'route' => '/member/center/orders',
    'params' => NULL,
    'sort' => 8,
    'status' => 1,
  ),
  42 => 
  array (
    'id' => 48,
    'title' => '搜索管理',
    'permission_code' => 'admin.config',
    'parent_id' => 2,
    'icon' => 'fa fa-search',
    'route' => '/system/search',
    'params' => NULL,
    'sort' => 21,
    'status' => 1,
  ),
  420 => 
  array (
    'id' => 49,
    'title' => '验证码',
    'permission_code' => 'admin.config',
    'parent_id' => 2,
    'icon' => 'fa fa-shield',
    'route' => '/system/captcha',
    'params' => NULL,
    'sort' => 23,
    'status' => 1,
  ),
  43 => 
  array (
    'id' => 50,
    'title' => '支付接口',
    'permission_code' => 'admin.config',
    'parent_id' => 2,
    'icon' => 'fa fa-credit-card',
    'route' => '/system/payment',
    'params' => NULL,
    'sort' => 20,
    'status' => 0,
  ),
  44 =>
  array (
    'id' => 970,
    'title' => '接口与提醒',
    'permission_code' => 'admin.config',
    'parent_id' => 2,
    'icon' => 'fa fa-plug',
    'route' => '/system/channels',
    'params' => NULL,
    'sort' => 19,
    'status' => 1,
  ),
  45 =>
  array (
    'id' => 51,
    'title' => '访问统计',
    'permission_code' => 'admin.stats.list',
    'parent_id' => 64,
    'icon' => 'fa fa-line-chart',
    'route' => '/site/stats',
    'params' => NULL,
    'sort' => 5,
    'status' => 1,
  ),
  450 => 
  array (
    'id' => 52,
    'title' => '自定表单',
    'permission_code' => 'admin.form.list',
    'parent_id' => 64,
    'icon' => 'fa fa-wpforms',
    'route' => '/site/form',
    'params' => NULL,
    'sort' => 2,
    'status' => 1,
  ),
  46 => 
  array (
    'id' => 53,
    'title' => '应用市场',
    'permission_code' => 'admin.plugin.list',
    'parent_id' => 16,
    'icon' => 'fa fa-cloud-upload',
    'route' => '/plugin/cloud',
    'params' => NULL,
    'sort' => 2,
    'status' => 1,
  ),
  47 => 
  array (
    'id' => 54,
    'title' => '已购买插件',
    'permission_code' => 'admin.plugin.list',
    'parent_id' => 16,
    'icon' => 'fa fa-shopping-cart',
    'route' => '/plugin/purchased',
    'params' => NULL,
    'sort' => 3,
    'status' => 1,
  ),
  48 => 
  array (
    'id' => 55,
    'title' => '已安装插件',
    'permission_code' => 'admin.plugin.list',
    'parent_id' => 16,
    'icon' => 'fa fa-puzzle-piece',
    'route' => '/plugin/mine',
    'params' => NULL,
    'sort' => 1,
    'status' => 1,
  ),
  49 => 
  array (
    'id' => 56,
    'title' => '新建插件',
    'permission_code' => 'admin.plugin.manage',
    'parent_id' => 16,
    'icon' => 'fa fa-plus',
    'route' => '/plugin/scaffold',
    'params' => NULL,
    'sort' => 4,
    'status' => 0,
  ),
  50 => 
  array (
    'id' => 94,
    'title' => '开发者工作台',
    'permission_code' => 'admin.plugin.manage',
    'parent_id' => 16,
    'icon' => 'fa fa-code',
    'route' => '/plugin/workbench',
    'params' => NULL,
    'sort' => 5,
    'status' => 1,
  ),
  51 => 
  array (
    'id' => 57,
    'title' => '经营看板',
    'permission_code' => 'admin.stats.list',
    'parent_id' => 64,
    'icon' => 'fa fa-dashboard',
    'route' => '/site/cockpit',
    'params' => NULL,
    'sort' => 4,
    'status' => 0,
  ),
  71 => 
  array (
    'id' => 62,
    'title' => '点赞与收藏',
    'permission_code' => 'admin.favorite.list',
    'parent_id' => 64,
    'icon' => 'fa fa-heart',
    'route' => '/site/favorite',
    'params' => NULL,
    'sort' => 5,
    'status' => 0,
  ),
  52 => 
  array (
    'id' => 64,
    'title' => '运营互动',
    'permission_code' => 'admin.site',
    'parent_id' => 0,
    'icon' => 'fa fa-bar-chart',
    'route' => '',
    'params' => NULL,
    'sort' => 28,
    'status' => 1,
  ),
  53 => 
  array (
    'id' => 71,
    'title' => '批量替换',
    'permission_code' => 'admin.document.edit',
    'parent_id' => 20,
    'icon' => 'fa fa-exchange',
    'route' => '/content/tools/bulk-replace',
    'params' => NULL,
    'sort' => 6,
    'status' => 1,
  ),
  54 => 
  array (
    'id' => 73,
    'title' => '系统升级',
    'permission_code' => 'admin.config',
    'parent_id' => 20,
    'icon' => 'fa fa-cloud-upload',
    'route' => '/system/upgrade',
    'params' => NULL,
    'sort' => 7,
    'status' => 1,
  ),
  55 => 
  array (
    'id' => 74,
    'title' => '微信小程序',
    'permission_code' => 'admin.config',
    'parent_id' => 2,
    'icon' => 'fa fa-weixin',
    'route' => '/system/miniprogram/wechat',
    'params' => NULL,
    'sort' => 24,
    'status' => 0,
  ),
  56 => 
  array (
    'id' => 75,
    'title' => '页面装修',
    'permission_code' => 'admin.config',
    'parent_id' => 74,
    'icon' => 'lucide:layout-template',
    'route' => '/system/miniprogram/decor',
    'params' => NULL,
    'sort' => 2,
    'status' => 1,
  ),
  57 => 
  array (
    'id' => 76,
    'title' => '产品中心',
    'permission_code' => NULL,
    'parent_id' => 0,
    'icon' => 'fa fa-cube',
    'route' => '',
    'params' => NULL,
    'sort' => 22,
    'status' => 1,
  ),
  58 => 
  array (
    'id' => 77,
    'title' => 'AI 配置',
    'permission_code' => 'admin.config',
    'parent_id' => 2,
    'icon' => 'fa fa-magic',
    'route' => '/system/ai-config',
    'params' => NULL,
    'sort' => 22,
    'status' => 1,
  ),
  59 => 
  array (
    'id' => 78,
    'title' => '悬浮联系',
    'permission_code' => 'admin.config',
    'parent_id' => 64,
    'icon' => 'fa fa-phone',
    'route' => '/system/float-contact',
    'params' => NULL,
    'sort' => 1,
    'status' => 1,
  ),
  60 => 
  array (
    'id' => 79,
    'title' => '多域名分站',
    'permission_code' => 'admin.site.domain',
    'parent_id' => 2,
    'icon' => 'fa fa-globe',
    'route' => '/site/domain',
    'params' => NULL,
    'sort' => 3,
    'status' => 1,
  ),
  61 => 
  array (
    'id' => 80,
    'title' => '网站栏目',
    'permission_code' => 'admin.site.nav',
    'parent_id' => 2,
    'icon' => 'fa fa-sitemap',
    'route' => '/site/nav',
    'params' => NULL,
    'sort' => 4,
    'status' => 0,
  ),
  62 => 
  array (
    'id' => 81,
    'title' => '单页管理',
    'permission_code' => 'admin.site.page',
    'parent_id' => 2,
    'icon' => 'fa fa-file-o',
    'route' => '/site/page',
    'params' => NULL,
    'sort' => 5,
    'status' => 0,
  ),
  63 => 
  array (
    'id' => 84,
    'title' => '超级搜索',
    'permission_code' => 'admin.config',
    'parent_id' => 2,
    'icon' => 'fa fa-bolt',
    'route' => '/system/search',
    'params' => NULL,
    'sort' => 22,
    'status' => 0,
  ),
  64 => 
  array (
    'id' => 87,
    'title' => '小程序',
    'permission_code' => 'admin.config',
    'parent_id' => 0,
    'icon' => 'fa fa-weixin',
    'route' => '',
    'params' => NULL,
    'sort' => 38,
    'status' => 1,
  ),
  65 => 
  array (
    'id' => 88,
    'title' => '渠道配置',
    'permission_code' => 'admin.config',
    'parent_id' => 87,
    'icon' => 'fa fa-cog',
    'route' => '/system/miniprogram/wechat',
    'params' => NULL,
    'sort' => 2,
    'status' => 0,
  ),
  66 => 
  array (
    'id' => 89,
    'title' => '页面装修',
    'permission_code' => 'admin.config',
    'parent_id' => 87,
    'icon' => 'fa fa-th-large',
    'route' => '/system/miniprogram/decor',
    'params' => NULL,
    'sort' => 3,
    'status' => 1,
  ),
  67 => 
  array (
    'id' => 90,
    'title' => '交付向导',
    'permission_code' => 'admin.config',
    'parent_id' => 87,
    'icon' => 'fa fa-map-signs',
    'route' => '/weapp/host/mp-wechat/guide',
    'params' => NULL,
    'sort' => 1,
    'status' => 1,
  ),
  68 => 
  array (
    'id' => 93,
    'title' => '导入插件',
    'permission_code' => 'admin.plugin.manage',
    'parent_id' => 16,
    'icon' => 'fa fa-upload',
    'route' => '/plugin/import',
    'params' => NULL,
    'sort' => 6,
    'status' => 0,
  ),
  710 => 
  array (
    'id' => 95,
    'title' => '数据保留策略',
    'permission_code' => 'admin.cron',
    'parent_id' => 20,
    'icon' => 'fa fa-archive',
    'route' => '/system/data-retention',
    'params' => NULL,
    'sort' => 2,
    'status' => 1,
  ),
  72 =>
  array (
    'id' => 972,
    'title' => '限流策略',
    'permission_code' => 'admin.cron',
    'parent_id' => 20,
    'icon' => 'fa fa-tachometer',
    'route' => '/system/rate-limit',
    'params' => NULL,
    'sort' => 3,
    'status' => 1,
  ),
  73 =>
  array (
    'id' => 960,
    'title' => '企业经营',
    'permission_code' => NULL,
    'parent_id' => 0,
    'icon' => 'fa fa-building',
    'route' => '',
    'params' => NULL,
    'sort' => 12,
    'status' => 0,
  ),
  730 =>
  array (
    'id' => 961,
    'title' => '（占位）协同办公',
    'permission_code' => 'plugin.oa.use',
    'parent_id' => 960,
    'icon' => 'fa fa-sitemap',
    'route' => '/weapp/host/oa/index',
    'params' => NULL,
    'sort' => 1,
    'status' => 0,
  ),
  74 =>
  array (
    'id' => 962,
    'title' => '（占位）客户关系',
    'permission_code' => 'plugin.crm.use',
    'parent_id' => 960,
    'icon' => 'fa fa-handshake-o',
    'route' => '/weapp/host/crm/index',
    'params' => NULL,
    'sort' => 2,
    'status' => 0,
  ),
  75 =>
  array (
    'id' => 963,
    'title' => '（占位）进销存',
    'permission_code' => 'plugin.erp.use',
    'parent_id' => 960,
    'icon' => 'fa fa-cubes',
    'route' => '/weapp/host/erp/index',
    'params' => NULL,
    'sort' => 3,
    'status' => 0,
  ),
  76 =>
  array (
    'id' => 964,
    'title' => '（占位）研发 PLM',
    'permission_code' => 'plugin.plm.use',
    'parent_id' => 960,
    'icon' => 'fa fa-pencil-square-o',
    'route' => '/weapp/host/plm/index',
    'params' => NULL,
    'sort' => 4,
    'status' => 0,
  ),
  77 =>
  array (
    'id' => 965,
    'title' => '（占位）制造执行',
    'permission_code' => 'plugin.mes.use',
    'parent_id' => 960,
    'icon' => 'fa fa-industry',
    'route' => '/weapp/host/mes/index',
    'params' => NULL,
    'sort' => 5,
    'status' => 0,
  ),
  78 =>
  array (
    'id' => 966,
    'title' => '品项列表',
    'permission_code' => 'admin.item.list',
    'parent_id' => 76,
    'icon' => 'fa fa-circle-o',
    'route' => '/product/item',
    'params' => NULL,
    'sort' => 1,
    'status' => 1,
  ),
  79 =>
  array (
    'id' => 967,
    'title' => '基本设置',
    'permission_code' => 'admin.item.list',
    'parent_id' => 76,
    'icon' => 'fa fa-circle-o',
    'route' => '/product/settings',
    'params' => NULL,
    'sort' => 2,
    'status' => 1,
  ),
  80 =>
  array (
    'id' => 968,
    'title' => '产品参数',
    'permission_code' => 'admin.item.list',
    'parent_id' => 76,
    'icon' => 'fa fa-circle-o',
    'route' => '/product/params',
    'params' => NULL,
    'sort' => 3,
    'status' => 1,
  ),
  81 =>
  array (
    'id' => 969,
    'title' => '提醒设置',
    'permission_code' => 'admin.config',
    'parent_id' => 2,
    'icon' => 'fa fa-bell-o',
    'route' => '/system/login-notice',
    'params' => NULL,
    'sort' => 24,
    'status' => 0,
  ),
  82 =>
  array (
    'id' => 973,
    'title' => 'SQL 控制台',
    'permission_code' => 'admin.sql_console',
    'parent_id' => 20,
    'icon' => 'fa fa-terminal',
    'route' => '/system/sql-console',
    'params' => NULL,
    'sort' => 8,
    'status' => 0,
  ),
);
